/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCarilerRouteImport } from './routes/_authenticated/cariler'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFaturalarRouteImport } from './routes/_authenticated/faturalar'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedStokRouteImport } from './routes/_authenticated/stok'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarilerRoute = AuthenticatedCarilerRouteImport.update({
  id: '/cariler',
  path: '/cariler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaturalarRoute = AuthenticatedFaturalarRouteImport.update({
  id: '/faturalar',
  path: '/faturalar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStokRoute = AuthenticatedStokRouteImport.update({
  id: '/stok',
  path: '/stok',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cariler': typeof AuthenticatedCarilerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturalar': typeof AuthenticatedFaturalarRoute
  '/pos': typeof AuthenticatedPosRoute
  '/stok': typeof AuthenticatedStokRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cariler': typeof AuthenticatedCarilerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/faturalar': typeof AuthenticatedFaturalarRoute
  '/pos': typeof AuthenticatedPosRoute
  '/stok': typeof AuthenticatedStokRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cariler': typeof AuthenticatedCarilerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/faturalar': typeof AuthenticatedFaturalarRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/stok': typeof AuthenticatedStokRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/cariler' | '/dashboard' | '/faturalar' | '/pos' | '/stok'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/cariler' | '/dashboard' | '/faturalar' | '/pos' | '/stok'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cariler'
    | '/_authenticated/dashboard'
    | '/_authenticated/faturalar'
    | '/_authenticated/pos'
    | '/_authenticated/stok'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cariler': {
      id: '/_authenticated/cariler'
      path: '/cariler'
      fullPath: '/cariler'
      preLoaderRoute: typeof AuthenticatedCarilerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faturalar': {
      id: '/_authenticated/faturalar'
      path: '/faturalar'
      fullPath: '/faturalar'
      preLoaderRoute: typeof AuthenticatedFaturalarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stok': {
      id: '/_authenticated/stok'
      path: '/stok'
      fullPath: '/stok'
      preLoaderRoute: typeof AuthenticatedStokRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarilerRoute: typeof AuthenticatedCarilerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFaturalarRoute: typeof AuthenticatedFaturalarRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedStokRoute: typeof AuthenticatedStokRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarilerRoute: AuthenticatedCarilerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFaturalarRoute: AuthenticatedFaturalarRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedStokRoute: AuthenticatedStokRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
